conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tavern.urls'))

]

tavern/urls.py
from django.urls import path

from . import views

app_name = 'tavern'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote/', views.VotesView.as_view(), name='vote'),

]

tavern/models.py
from django.db import models
import datetime


class Lunch(models.Model):
    nickname = models.CharField(max_length=100, default='')
    user = models.CharField(max_length=100, default='')
    date = models.DateField(max_length=100, default=datetime.date.today)

    def __str__(self):
        return self.nickname


class Location(models.Model):
    lunch = models.ForeignKey('tavern.Lunch', on_delete=models.CASCADE, null=True)
    restaurant_suggestions = models.CharField(max_length=100, null=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.restaurant_suggestions

tavern/views.py
from django.urls import reverse
from .models import Lunch
from .models import Location
from django.views.generic import TemplateView, View
from django.http import HttpResponseRedirect


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        lunches = Lunch.objects.all()

        context = {
            'lunches': lunches

        }
        return context


class DetailView(TemplateView):
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        lunch_pk = self.kwargs.get('pk')
        lunch = Lunch.objects.get(pk=lunch_pk)
        locations = Location.objects.filter(lunch__pk=lunch_pk)

        context = {
            'locations': locations,
            'lunch': lunch
        }
        return context


class ResultsView(TemplateView):
    template_name = 'results.html'

    def get_context_data(self, **kwargs):
        lunch_pk = self.kwargs.get('pk')
        lunch = Lunch.objects.get(pk=lunch_pk)
        locations = Location.objects.filter(lunch__pk=lunch_pk)

        context = {
            'locations': locations,
            'lunch': lunch
        }
        return context


class VotesView(View):
    def post(self, request, **kwargs):
        lunch_pk = self.kwargs.get('pk')
        lunch = Lunch.objects.get(pk=lunch_pk)
        location_voted_for_id = self.request.POST.get('location')
        selected_location = lunch.location_set.get(pk=location_voted_for_id)
        selected_location.votes += 1
        selected_location.save()
        results_url = reverse('tavern:results', args=(lunch.pk,))
        return HttpResponseRedirect(results_url)

tavern/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
              crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" class="stylesheet">

        <title>Tavern</title>
    </head>
    <body>
        <div class="container">
            <header>
                <a href="{% url 'tavern:home' %}" class="logo" type="">Tavern</a>
                <p class="create_poll">Create Poll</p>
            </header>
            <div class="container">

                {% block content %}


                {% endblock %}
            </div>
            <footer class="footer">
                &copy; 2019 Tavern, Inc
            </footer>
        </div>
    </body>
</html>

tavern/templates/detail.html
{% extends 'base.html' %}

{% block content %}

   <p class="lunch-name"> {{ lunch.nickname }}</p>
<table>
    {% for location in locations %}
     <tr> 
        <td class="lunch-suggestions">{{ location.restaurant_suggestions }}</td>
         <td>
             <form action="{% url 'tavern:vote' lunch.id %}" method="post">
                 {% csrf_token %}
                 <input type="hidden" name="location" value="{{ location.id }}">
                 <input type="submit" name="submit_button" value="Vote">
             </form>
         </td>
     </tr>
    {% endfor %}

</table>
{% endblock %}

{#add button to vote on lunch location#}

tavern/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <img src="../static/photos/iStock-502840530.jpg" alt="#" height="600px" width="800px" class="img">
    <p>Which lunch group would you like to enter?</p>

    <table>
        {% for lunch in lunches %}
            <tr>
                <td>
                    <a href="{% url 'tavern:detail' lunch.id %}">{{ lunch.nickname }}
                    </a>
                </td>

                <td>(<em>Created by: {{ lunch.user }}</em>)</td>
                    <td>on {{ lunch.date }}</td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

tavern/templates/results.html
{% extends 'base.html' %}

{% block content %}

<table>
    {% for location in locations %}
        <tr>
        <td>{{ location }}</td>
       <td>{{ location.votes }}</td>
        </tr>
    {% endfor %}
    <a class='logo' href="{% url 'tavern:home' %}">Return Home</a>
</table>
{% endblock %}